[tool.poetry]
name = "overseer mdp broker"
version = "0.1.0"
description = "Asynchronous implementation of the Majordomo broker"
authors = ["Void-ux <77840397+Void-ux@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
pyzmq = "^25.1.0"
msgpack = "^1.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
